#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v25
# autospec commit: 9594167
#
Name     : R-profmem
Version  : 0.7.0
Release  : 25
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/profmem_0.7.0.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/profmem_0.7.0.tar.gz
Summary  : Simple Memory Profiling for R
Group    : Development/Tools
License  : LGPL-2.1+
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%prep
%setup -q -n profmem
pushd ..
cp -a profmem buildavx2
popd
pushd ..
cp -a profmem buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1746463120

%install
export SOURCE_DATE_EPOCH=1746463120
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/profmem/DESCRIPTION
/usr/lib64/R/library/profmem/INDEX
/usr/lib64/R/library/profmem/Meta/Rd.rds
/usr/lib64/R/library/profmem/Meta/features.rds
/usr/lib64/R/library/profmem/Meta/hsearch.rds
/usr/lib64/R/library/profmem/Meta/links.rds
/usr/lib64/R/library/profmem/Meta/nsInfo.rds
/usr/lib64/R/library/profmem/Meta/package.rds
/usr/lib64/R/library/profmem/Meta/vignette.rds
/usr/lib64/R/library/profmem/NAMESPACE
/usr/lib64/R/library/profmem/NEWS.md
/usr/lib64/R/library/profmem/R/profmem
/usr/lib64/R/library/profmem/R/profmem.rdb
/usr/lib64/R/library/profmem/R/profmem.rdx
/usr/lib64/R/library/profmem/WORDLIST
/usr/lib64/R/library/profmem/doc/index.html
/usr/lib64/R/library/profmem/doc/profmem.html
/usr/lib64/R/library/profmem/doc/profmem.md.rsp
/usr/lib64/R/library/profmem/extdata/broken.Rprofmem.out
/usr/lib64/R/library/profmem/extdata/example.Rprofmem.out
/usr/lib64/R/library/profmem/help/AnIndex
/usr/lib64/R/library/profmem/help/aliases.rds
/usr/lib64/R/library/profmem/help/paths.rds
/usr/lib64/R/library/profmem/help/profmem.rdb
/usr/lib64/R/library/profmem/help/profmem.rdx
/usr/lib64/R/library/profmem/html/00Index.html
/usr/lib64/R/library/profmem/html/R.css
/usr/lib64/R/library/profmem/tests/capableOfProfmem.R
/usr/lib64/R/library/profmem/tests/exceptions.R
/usr/lib64/R/library/profmem/tests/profmem,error.R
/usr/lib64/R/library/profmem/tests/profmem,nested.R
/usr/lib64/R/library/profmem/tests/profmem.R
/usr/lib64/R/library/profmem/tests/readRprofmem.R
